Repository dfinity/ic-js, pull requests merged in 2023-11, with the labels that each got.

#464 docs: fix typo in ledger-icrc README
  packages/ledger-icrc/README.md
Labels: documentation

#466 feat: ICP index canister getTransactions
  CHANGELOG.md
  packages/ledger-icp/README.md
  packages/ledger-icp/src/errors/index.errors.ts
  packages/ledger-icp/src/index.canister.spec.ts
  packages/ledger-icp/src/index.canister.ts
  packages/ledger-icp/src/index.ts
  packages/ledger-icp/src/types/index.params.ts
Labels: enhancement

#467 feat: seconds to duration
  package.json
  packages/utils/README.md
  packages/utils/src/index.ts
  packages/utils/src/utils/date.utils.spec.ts
  packages/utils/src/utils/date.utils.ts
Labels: enhancement

#474 Chore: Upgrade didc
  .github/workflows/checks.yml
  CHANGELOG.md
  packages/ckbtc/candid/minter.d.ts
  packages/cmc/candid/cmc.d.ts
  packages/ic-management/README.md
  packages/ic-management/candid/ic-management.d.ts
  packages/ledger-icp/candid/index.d.ts
  packages/ledger-icp/candid/ledger.d.ts
  packages/ledger-icrc/README.md
  packages/ledger-icrc/candid/icrc_index.d.ts
  packages/ledger-icrc/candid/icrc_ledger.d.ts
  packages/ledger-icrc/src/utils/ledger.utils.ts
  packages/nns/candid/governance.d.ts
  packages/nns/candid/governance_test.d.ts
  packages/nns/candid/sns_wasm.d.ts
  packages/nns/src/canisters/governance/response.converters.ts
  packages/sns/candid/sns_governance.d.ts
  packages/sns/candid/sns_governance_test.d.ts
  packages/sns/candid/sns_root.d.ts
  packages/sns/candid/sns_swap.d.ts
  packages/sns/src/sns.wrapper.ts
  packages/sns/src/types/actions.ts
  packages/sns/src/types/governance.params.ts
  scripts/compile-idl-js
Labels: Planned

#480 Chore: Change "?" for "Option" for optional fields
  CHANGELOG.md
  packages/nns/src/canisters/governance/response.converters.ts
  packages/nns/src/types/governance_converters.ts
Labels: Planned

#487 docs: governance canister local snippet
  packages/nns/README.md
Labels: documentation

#486 feat: makeProposal return created proposal ID
  packages/nns/README.md
  packages/nns/src/canisters/governance/services.ts
  packages/nns/src/governance.canister.spec.ts
  packages/nns/src/governance.canister.ts
Labels: enhancement
